### ISSUE TITLE
Tx screen, account index is used in the `from`, but ethereum address is used in the `to`, is that OK?

### ISSUE THREAD

**Issue by mmilenkovic** [hermeznetwork/batch-explorer#109]
On tx screen, account index is used in the `from`, but ethereum address is used in the `to`. I guess that they should have same behaviour

![](https://i.imgur.com/hxLxPOJ.png)

@Arnau I have the following code `transactionTask.data.type === 'Exit' ? transactionTask.data.toAccountIndex : transactionTask.data.toHezEthereumAddress` since the desing had it like that.

![](https://i.imgur.com/fvv5TQl.png)

> Q: Do you think this makes sense or not?

==Arnau answer:== No. For me what makes sense is to use always the same (ethereum address vs account index), unless it's not posible This is not what's happening here.
It's impossible to use always just eth or just idx, you will face nulls no matter what.
Let me know what product team prefers to use by default, and I'll let you know which cases are incompatible and have to be treated specially.

**Comment by rafal-na** [comment]
In the Ethereum ecosystem, users and developers are familiar with the Eth address. Therefore, to facilitate their integration and a smooth transition to Hermez L2, I would suggest:

1. To use Ethereum address as primary reference for transfers metadata.
2. idx can be used as supportive reference.
3. In the absence of an Eth address, idx may be used.

**Comment by rafal-na** [comment]
An alternative solution would be to always use Hermez main BJJ address and linked (derived) ETH address if it exists (below the BJJ).

**Comment by rafal-na** [comment]
As a result of the April 6 meeting, it was decided that Ethereum would be the primary address, and in the absence of Ethereum, that it would be BJJ.
