### ISSUE TITLE
Modifications related to 0xFF... ethereum account

### ISSUE THREAD

**Issue by ARR552** [hermeznetwork/batch-explorer#184]
Hello,

When a transferToBjj is performed the details showed in the batch explorer are:
https://explorer.testnet.hermez.io/transaction/0x02ee9ba80ca6592df6aa983a4be6a17a4e2ba1c6cfaf8b0837d0862e4e87794941
As you can see, the field "to" should be the bjj instead the ethereum address because in this case the ethereum address doesn't exist. Also, maybe we can show the new account index in the same way we are showing the field "from".

Another thing to take in account is the filter by ethereum address. When you want to see all the accounts associated to a ethereum address (you can check it in this link https://explorer.testnet.hermez.io/user-account/hez:0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF), you see the ethereum address and the bjj on the top. However, the bjj is wrong because each of the accounts can have different bjjs. I think that the bjj showed is the one associated to the first account but the second account might have a different bjj.

**Comment by rafal-na** [comment]
We can have `one main Hermez address`/account based on BJJ `and associated identifiers` such as:

- derived ETH address from the main BJJ
- another BJJ and ETH address
- all token accounts (related to above addresses?)

**Comment by mmilenkovic** [comment]
@rafal-na is working on the layout change.

**Comment by rafal-na** [comment]
I suggest changing from `User address` to `Account address` as not every address can belong to the user and separate the primary address from other account identifiers:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/47251577/113923847-52f69d00-97e9-11eb-965c-5b70a513ba39.png">

**Comment by rafal-na** [comment]
If the Ethereum address does not exist we can use `was not created` or `not registered` label:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/47251577/113996779-c7682500-9857-11eb-8bb7-9d82314bc20d.png">

**Comment by rafal-na** [comment]
If the transfer was made from an Ethereum address to an account that does not have an Ethereum address, we can indicate that the tokens were sent to a BJJ address a.k.a `Hermez internal address`:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/47251577/113997418-69880d00-9858-11eb-88a1-21a3428ebcba.png">
