### ISSUE TITLE
Handle transaction CreateAccountDepositTransfer

### ISSUE THREAD

**Issue by krlosMata** [hermeznetwork/batch-explorer#185]
`CreateAccountDepositTransfer` transaction type is an L1 transaction type an involves an account creation where the `depositAmount` is different than 0 and `amount` will different than 0 as well.
[Docs link](https://docs.hermez.io/#/developers/protocol/hermez-protocol/protocol?id=createaccountdeposittransfer)

Wallet does not support this transaction type but any user could perform this transaction and I think batch-explorer does not support it. In `Transactions` tab, only one amount is shown. So, in case of `CreateAccountDepositTransfer` I'm not sure which amount will be showed, `depositAmount` or `amount`

Same happens with [`DepositTranfer`](https://docs.hermez.io/#/developers/protocol/hermez-protocol/protocol?id=deposittransfer)

**Comment by mmilenkovic** [comment]
We have this piece of code to decide the amount we will show for a transaction (we based it on the API response):
![Screenshot 2021-05-11 at 00.10.43.png](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/87ce66b9-6525-4adb-bbc3-6c1e772af68f)

@krlosMata Do you think this is valid or we should take care of it differently?

**Comment by krlosMata** [comment]
For L2 transactions, `transaction.amount` is ok since L2 transactions involves only an amount transferred from account A to account B in layer 2.
However, in L1 transactions there are two kind of amounts: `depositAmount`(from L1 to L2) & `amount`(L2 to L2).
- `depositAmount` is used in tx types `Deposit`, `CreateAccountDeposit`, `CreateAccountDepositTransfer` & `DepositTransfer`
- `amount` is used in `CreateAccountDepositTransfer`, `DepositTransfer`, `forceTransfer` & `forceExit`

Therefore, `CreateAccountDepositTransfer` & `DepositTransfer` transactions types has both values. This transactions are not currently supported in `wallet-ui` but still users may perform them my calling directly the contract and thus I think It should be handle by the `batch-explorer`.

I add here and example:
`UserA` performs a `CreateAccountDepositTransfer` where it loads 100 and transfers 42 to `UserB`.
Transaction would be type `CreateAccountDepositTransfer` with `loadAmount = 100` and `amount = 42`.
Batch-explorer will print just one of this values, according to current code it will be `amount` and will not show information regarding `loadAmount`

**Comment by mmilenkovic** [comment]
@chamian Is it OK that in cases of `CreateAccountDepositTransfer` & `DepositTransfer` (as Carlos explained above) we show both `amount` and `load amount`?
And if yes what should be the label for `load amount`?

**Comment by chamian** [comment]
@mmilenkovic Yes, for these cases we should show both `amount` and `load amount`.For `load amount` we can label it as `Deposit amount`

**Comment by mmilenkovic** [comment]
Thanks @chamian
