### ISSUE TITLE
Bidding information

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/batch-explorer#196]
When the explorer lists the winning bids made by a coordinator, the column `bids` seems to display the total number of bids made by that coordinator. This number is repeated in all items in the list, and doesn’t seem to be necessary to display the same information for every item. Maybe it would make more sense to display the number of bids done for that particular slot?

**Comment by druiz0992** [comment]
![Uploading DEE06692-8DD1-4FF1-ACFB-15501466EBAD.png…]()

**Comment by mmilenkovic** [comment]
Pending Product decision.

**Comment by chamian** [comment]
@mmilenkovic I agree. That table is informing about slots and not coordinators. It makes sense to provide information about total bids for each slot.

**Comment by mmilenkovic** [comment]
@chamian and @mmilenkovic raised some concerns about if this column is needed at all. Chami will look into it and we'll make a decision.

**Comment by mmilenkovic** [comment]
As agreed with @chamian we will remove the `bids` column.
