### ISSUE TITLE
Tracking transfer to BJJ

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/batch-explorer#199]
When doing a transfer to a BJJ account from the wallet, the wallet displays BJJ as the destintioon account. However, explorer lists HezEthereumAddress (0xffff..ffff) as destination address and it makes difficult to track. Can we make explorer show BJJ?

**Comment by druiz0992** [comment]
![Screenshot from 2021-04-27 16-05-37](https://user-images.githubusercontent.com/46495002/116255697-c9484880-a772-11eb-8388-aff99ea655f2.png)

**Comment by mmilenkovic** [comment]
First a notice, since the last changes we are not showing the accountIndex neither in `from` nor `to`.

Second, when I make transaction to BJJ the response from the API has the following:
![Screenshot 2021-04-27 at 16.49.08.png](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/5805d9b6-5e4d-4ab1-bae5-adee3294a951)

Having the *fromBJJ* the same as *toBJJ*, as well as *fromHezEthereumAddress* being the same as *toHezEthereumAddress*.

My question is @druiz0992 @rafal-na what we should show in this case?

**Comment by mmilenkovic** [comment]
Related with https://github.com/hermeznetwork/batch-explorer/issues/184

**Comment by druiz0992** [comment]
The account I showed is an internal account with no hezEtherAddress so it’s not the same as the example shown by @mmilenkovic.

If I do a transfer to a BJJ, it would be better if I can track the address to which I made the transfer (BJJ). If I do a transfer to a hezEtherAddress, then I would show hezEtherAddress. If it is too confusing because we display different address types as the `to`, then I would just show both.

**Comment by mmilenkovic** [comment]
@rafal-na Do you agree with the comment above?

**Comment by druiz0992** [comment]
Hi, can we take a decision about this?

**Comment by mmilenkovic** [comment]
@rafal-na @chamian Please advise.

**Comment by mmilenkovic** [comment]
Finally we addresses are handled like this (all rules valid for both from and to):

1. If there is hermez ethereum address we show that
2. If there is no hermez ethereum address and there is BJJ address, we show BJJ address with additional label `(Hermez internal address)`
3. If there is no hermez ethereum address nor BJJ address, we snow nothing

**Comment by druiz0992** [comment]
But this doesn't completely resolve the issue. If a transfer is made to a BJJ account, even though there is an associated HEZ account as well, I would like the explorer to show the BJJ so that the person that did the transfer can verify it easily (destination address is the same as the one shown in the transaction state)

**Comment by mmilenkovic** [comment]
@chamian Can we show both then?

**Comment by mmilenkovic** [comment]
I talked to Chami. We will always show BJJ, so the rules will be (all rules valid for both from and to):

1. If there is BJJ address we show it with additional label (Hermez internal address)
2. If there is no BJJ address and there is hermez ethereum address, we show hermez ethereum address
3. If there is no hermez ethereum address nor BJJ address, we snow nothing

**Comment by druiz0992** [comment]
@mmilenkovic thanks!!
