### ISSUE TITLE
Add Batch number information to transaction info

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/batch-explorer#200]
When displaying transaction information, can we have an additional info section where batch number is diplayed (if the transactions has been forged)?

**Comment by elias-garcia** [comment]
I think that the batch number is already being displayed in the `transaction information` screen:

You need to click in the `View details` button as shown below:

![Captura de pantalla 2021-04-21 a las 17 27 03](https://user-images.githubusercontent.com/6737805/115583323-14bdab00-a2ca-11eb-9c04-99c79da6b8e8.png)

And then you will be able to see the `Included in batch` column:

![Captura de pantalla 2021-04-21 a las 17 48 04](https://user-images.githubusercontent.com/6737805/115583419-299a3e80-a2ca-11eb-9ece-94def1d9471a.png)

Maybe I'm missing something @druiz0992, let me know!

**Comment by mmilenkovic** [comment]
Blocked - waiting more info from @druiz0992

**Comment by druiz0992** [comment]
How come it is not shown here (https://explorer.internaltestnet.hermez.io/transaction/0x024aab30b0bd33568ee8c6f51b6c0655abfb802c389e53b19df24edea9be0373d0)
![Screenshot from 2021-04-27 16-05-37](https://user-images.githubusercontent.com/46495002/116255389-7a021800-a772-11eb-95e0-61d790ed859e.png)

**Comment by mmilenkovic** [comment]
@druiz0992 I will check.

**Comment by mmilenkovic** [comment]
@druiz0992 I am looking at the same transaction https://explorer.internaltestnet.hermez.io/transaction/0x024aab30b0bd33568ee8c6f51b6c0655abfb802c389e53b19df24edea9be0373d0

And I see this in the details:
<img width="895" alt="Screenshot 2021-04-27 at 16 13 23" src="https://user-images.githubusercontent.com/2448210/116256497-86d33b80-a773-11eb-8aef-f587f2e0b8d4.png">

Very strange. May it be that the batch info is not present in the API response at the first time, and later it is?

**Comment by mmilenkovic** [comment]
Which browser/OS are you using?

**Comment by druiz0992** [comment]
Weird in deed. I use chrome

**Comment by mmilenkovic** [comment]
Chrome is verified in different OS and seems to work fine.

@druiz0992 Could we reproduce this somehow? Any specific account or transaction type?

**Comment by druiz0992** [comment]
Just send a transfer with the wallet, wait till transaction is processed, then in the wallet:
Sent -> View in Explorer -> Details

**Comment by druiz0992** [comment]
I understand what's going on.

The explorer first attempts to fetch this information from the transaction-pool. If it fails, then checks in the transaction.history.
Batch number is not available in transaction pool, but it is in transaction.history.

I would change the flow. First check transaction pool. If transaction is not forged, then display info and do not retry.  If transaction is forged, then call transaction history.
