### ISSUE TITLE
Remove `Eth Block Hash` in every view

### ISSUE THREAD

**Issue by krlosMata** [hermeznetwork/batch-explorer#201]
This is not a bug but just an information that may not be very useful.

`Eth Block Hash` is shown but that value can not be used in etherscan to look for the block number and also `Eth Block Number` is shown and it has the link incorporated to etherscan. Thus, it feels that `Eth Block Hash` does not add any useful information.

The proposal would be to remove it from information or change for `tx hash`

**Comment by mmilenkovic** [comment]
Pending Product opinion.

**Comment by mmilenkovic** [comment]
@rafal-na @chamian Any thoughts on this?

**Comment by mmilenkovic** [comment]
@krlosMata What do you mean by a `tx hash` above in the comment?

**Comment by krlosMata** [comment]
This would be a transaction hash link in etherscan:
https://etherscan.io/tx/0x0c2d1cf0d7ffd450408810f9f8635ad2e4fd3eafbd792b8fb636f12831958961

It is a unique identifier for an ethereum transaction.
My suggestion is to add this identifier (`txHash`) instead of the ethereum block hash, which includes hermez `forgeBatch` transactions and other block transactions.
With `txHash` we could add a direct link to etherscan as well, similar to what it is done in `eth block number` field

**Comment by elias-garcia** [comment]
I agree with @krlosMata, i think that the `Ethereum Tx Hash` would provide better information for the end user than the `block hash`. You can still see the block information from the Etherscan transaction.

**Comment by mmilenkovic** [comment]
@krlosMata Just to be clear, /batches/{batchNum} returns:
<img width="698" alt="Screenshot 2021-05-03 at 22 39 15" src="https://user-images.githubusercontent.com/2448210/116930770-784bbf00-ac60-11eb-9780-01e9e19b1643.png">

so, do you propose to create a link from `ethereumBlockHash`? Something like https://etherscan.io/tx/{ethereumBlockHash} ?

Or you are referring to some other identifier when you say `txHash`? And if yes to which exactly?

**Comment by krlosMata** [comment]
No, `ethereumBlockHash` and `txHash` are different identifiers. I propose to use `txHash` which is a hash that identifies uniquely a transaction in ethereum, such as https://etherscan.io/tx/0x0c2d1cf0d7ffd450408810f9f8635ad2e4fd3eafbd792b8fb636f12831958961
`ethereumBlockHash` identifies uniquely a block in ethereum and it canot be search in etherscan with https://etherscan.io/tx/{ethereumBlockHash}. Etherscan allows search by `blockNumber` not by `ethereumBlockHash`

**Comment by mmilenkovic** [comment]
But we are talking here about the Batch view, there is no `txHash` for a Batch if I'm not mistaking.

So, for Batch page we can remove `ethereumBlockHash` and leave `blockNumber` and for Transaction page we leave `txHash` is that correct?

**Comment by krlosMata** [comment]
I'm referring to the `txHash` as the Ethereum transaction hash where the batch is forged, it is different than the L2 transactions view.
By inspecting the API response, I would suggest to return the `txHash` instead of `ethereumBlockHash` in the batch information

**Comment by krlosMata** [comment]
Added issue in `hermez-node` repository: https://github.com/hermeznetwork/hermez-node/issues/789

**Comment by mmilenkovic** [comment]
Blecked by https://github.com/hermeznetwork/hermez-node/issues/789
