### ISSUE TITLE
Pending withdraw marked as completed in explorer

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/batch-explorer#227]
Withdraw is marked as pending in wallet, but marked s `Completed`
![1](https://user-images.githubusercontent.com/46495002/117618076-bae42e80-b16d-11eb-92e3-6d1f73af68d5.png)
![2](https://user-images.githubusercontent.com/46495002/117618138-cdf6fe80-b16d-11eb-9da9-4bdcf8d701a7.png)

**Comment by druiz0992** [comment]
It seems this `Completed` refers to the first part of the withdraw transaction. I find it confusing because it leads to think that the full transaction has finished.

**Comment by druiz0992** [comment]
I am fine not dong anything here. I just want to ask if anyone believes this is misleading, and if so, what do you believe we could do to improve?

**Comment by AlbertoElias** [comment]
It may be misleading yes, but I have no idea what's the best way to solve this. BE markes as completed the first step, the Exit. The Batch Explorer has no way of knowing what happens with the Withdrawal step, which is a L2 transaction.

**Comment by elias-garcia** [comment]
Yes... Maybe we can show more information when a withdraw has been completed, like a `?` button next to the `Completed` label, to inform that the user how withdraws work... At the end in the batch explorer we don't have information to track the L1 transaction, only in the wallet as @AlbertoElias said.

**Comment by mmilenkovic** [comment]
@chamian What do you think about comment above (one from @elias-garcia )?

**Comment by druiz0992** [comment]
Another suggestion would be to say Ẁithdraw is completed in L2?

**Comment by mmilenkovic** [comment]
![Screenshot 2021-05-12 at 16.31.04.png](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/479f739d-955a-4320-a414-4c940eda803c)

**Comment by mmilenkovic** [comment]
![Screenshot 2021-05-25 at 12.02.35.png](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/36b01b64-0e7b-46dd-9b7a-a9a6cfa28796)
