### ISSUE TITLE
Display coordinator version

### ISSUE THREAD

**Issue by elias-garcia** [hermeznetwork/batch-explorer#232]
Display the coordinator version in the coordinator view

**Comment by mmilenkovic** [comment]
@elias-garcia Do you know where I can get the coordinator version info?

**Comment by mmilenkovic** [comment]
![Screenshot 2021-07-04 at 17.37.55.png](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/6845bfef-5a12-4ef7-95b4-bd51e4a9bdd4)
