### ISSUE TITLE
Typo in BAT Token listing

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/batch-explorer#250]
BAT token is described as `Basic Attention Toke` in https://explorer.hermez.io/tokens

**Comment by mmilenkovic** [comment]
![Screenshot 2021-06-14 at 15.57.04.png](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/39b42251-a863-42b0-894a-d80db45ff492)

Typo comes from the API.

**Comment by mmilenkovic** [comment]
Issue moved to [hermeznetwork/hermez-node #874](https://github.com/hermeznetwork/hermez-node/issues/874) via [**ZenHub**](https://www.zenhub.com/)
