### ISSUE TITLE
Status Slot Bug

### ISSUE THREAD

**Issue by laisolizq** [hermeznetwork/batch-explorer#251]
## Summary of Bug

On the information page of a slot (for example https://explorer.testnet.hermez.io/slot/13203) always appears that the status is "open Auction". Although the API returns that it is already closed (http://api.testnet.hermez.io/v1/slots/13203).

 Code: https://github.com/hermeznetwork/batch-explorer/blob/main/src/views/slot/components/slot-details/slot-details.view.jsx#L10

**Comment by mmilenkovic** [comment]
Seems there was `closedAuction` parameter before, we will change this.

**Comment by laisolizq** [comment]
I think yes, because there are no bids in that slot: http://api.testnet.hermez.io/v1/bids?slotNum=13203
An example from `internaltestnet`:
For example, when there is a bid in a slot: https://api.internaltestnet.hermez.io/v1/slots/4297
Has a `bestBid` in the response: https://api.internaltestnet.hermez.io/v1/slots/4297
