### ISSUE TITLE
Coordinator and batch Information bug

### ISSUE THREAD

**Issue by laisolizq** [hermeznetwork/batch-explorer#252]
## Summary of Bug

If you search in the search bar a valid coordinator address and then you change it to an invalid coordinator address:
- Coordinator info is correct, you can see: "An error occurred. Coordinator does not exist or cannot be loaded"
- But the "forged batches" are the same as in the first search

The same happens in batch page when you first search a correct batch and then a wrong batch.

**Comment by mmilenkovic** [comment]
After talking to @elias-garcia we decided to refactor the search. Handle search will be moved to a new thunk so calls can be done asynchronous.
